package com.cyc.ssm.bean;

public class Book {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_id
     *
     * @mbggenerated Thu Mar 31 20:00:46 CST 2022
     */
    private Integer bookId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_name
     *
     * @mbggenerated Thu Mar 31 20:00:46 CST 2022
     */
    private String bookName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.book_count
     *
     * @mbggenerated Thu Mar 31 20:00:46 CST 2022
     */
    private Integer bookCount;

    public Book() {
    }

    public Book(Integer bookId, String bookName, Integer bookCount) {
        this.bookId = bookId;
        this.bookName = bookName;
        this.bookCount = bookCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_id
     *
     * @return the value of book.book_id
     *
     * @mbggenerated Thu Mar 31 20:00:46 CST 2022
     */
    public Integer getBookId() {
        return bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_id
     *
     * @param bookId the value for book.book_id
     *
     * @mbggenerated Thu Mar 31 20:00:46 CST 2022
     */
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_name
     *
     * @return the value of book.book_name
     *
     * @mbggenerated Thu Mar 31 20:00:46 CST 2022
     */
    public String getBookName() {
        return bookName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_name
     *
     * @param bookName the value for book.book_name
     *
     * @mbggenerated Thu Mar 31 20:00:46 CST 2022
     */
    public void setBookName(String bookName) {
        this.bookName = bookName == null ? null : bookName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.book_count
     *
     * @return the value of book.book_count
     *
     * @mbggenerated Thu Mar 31 20:00:46 CST 2022
     */
    public Integer getBookCount() {
        return bookCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.book_count
     *
     * @param bookCount the value for book.book_count
     *
     * @mbggenerated Thu Mar 31 20:00:46 CST 2022
     */
    public void setBookCount(Integer bookCount) {
        this.bookCount = bookCount;
    }

    @Override
    public String toString() {
        return "Book{" +
                "bookId=" + bookId +
                ", bookName='" + bookName + '\'' +
                ", bookCount=" + bookCount +
                '}';
    }
}